### ISSUE TITLE
show method improvements

### ISSUE THREAD

**Issue by drighelli** [drighelli/SpatialExperiment#13]
- [x] remove `inTissue` it seems to be unuseful
- [ ] remove `spatialCoordsNames` because it's redundant

**Comment by lmweber** [comment]
After thinking about it some more - I think we do need either `spatialCoordNames` or something else that shows the column names of `spatialCoords`. Otherwise this is not shown anywhere in the show method.

The best option I think would be to show it as a line beginning with `spatialCoords`, e.g. as in the example below.

In this example, I have replaced the existing lines `spatialCoordsNames` and `inTissue` with a new line `spatialCoords names(3) : x_coord y_coord in_tissue`. Not sure how hard this will be to implement though.

```
class: SpatialExperiment 
dim: 32285 2702 
metadata(0):
assays(1): counts
rownames(32285): ENSMUSG00000051951 ENSMUSG00000089699 ... ENSMUSG00000095019 ENSMUSG00000095041
rowData names(3): gene_id gene_name feature_type
colnames(2702): AAACAAGTATCTCCCA-1 AAACAATCTACTAGCA-1 ... TTGTTTCCATACAACT-1 TTGTTTGTGTAAATTC-1
colData names(9): barcode_id array_row ... y_coord in_tissue
reducedDimNames(0):
altExpNames(0):
spatialCoords names(3) : x_coord y_coord in_tissue
imgData(6): sample_id image_id ... height scaleFactor
```

**Comment by drighelli** [comment]
Replacing it as suggested by Lukas!
