### ISSUE TITLE
Remove argument as_df in spatialData()

### ISSUE THREAD

**Issue by HelenaLC** [drighelli/SpatialExperiment#44]
**Issue:**
I wonder whether we should remove `as_df = TRUE/FALSE` from `spatialData()`, as it in my opinion only adds room for instability and confusion (e.g., I had some issues unit-testing this because `matrix`/`data.frame`/`DFrame` conversions have the potential to alter row/column names). 

**Proposal**
Previously, `spatialData` were part of `colData`, which are anyways fixed to a `DFrame`; and the `colData` accessor accesses the corresponding slot *without* the option to convert to another output class. Now that `spatialData` were moved to a separate slot, I think they should behave exactly the same, i.e., fixed to a `DFrame` with a simple accessor that does not allow for conversion. We originally only had the (default) option to return a matrix in `spatialCoords` to facilitate interoperability with `spatstats`, but I see no motivation to have a similar argument in `spatialData`. Similarly, the replacement method should only allow a `DFrame`, as does `colData<-`, in order to be consistent and non-confusing.

**Comment by lmweber** [comment]
I think this makes sense. I think we included this in `spatialData()` because we also had it in `spatialCoords()`. But having it in `spatialData()` doesn't really add anything (since this is not used for `spatstats`) and potentially creates confusion.

In fact this has also led to [this recently opened issue](https://github.com/LieberInstitute/spatialLIBD/issues/10) in `spatialLIBD` package - i.e. related to the previous question of whether to return `data.frame` or `DataFrame`.

I agree `spatialData()` should return the same format/class as `colData()`, so removing the argument here would make things simpler.

**Comment by drighelli** [comment]
Sorry, but I think there is a design error in this method.

I agree that it has to return a DataFrame as default, but I still think that the `as.df` argument could be maintained to simplify the life of the others.

Just because, most of the visualization software doesn't work with `DataFrame`, but only with `data.frame` (I think it's the same idea that below the `spatialCoords` method that returns a `matrix`).

Generally speaking, I think we should be consistent with across all the methods and across the classes (as I think Helena was suggesting).

Anyway, this is only my point of view. If you prefer the other way, we can remove the argument.

**Comment by lmweber** [comment]
Yes, I can see arguments on both sides.

I think on balance it is best to return the same class as `colData()` for consistency. This means that some visualization functions will need to include `as.data.frame()`, but this is also the case now for visualization functions that use columns in `colData` (e.g. `sum` or `detected` from `scater` package). So in my view this is okay.

**Comment by HelenaLC** [comment]
Hm... I don't really see the issue. Long ago, I had simply written all spatial data into the `colData`: None of these are really special in my opinion, and I don't see why we'd want a designated slot for them in the first place. The exception are the spatial coordinates, which, in principle, might as well be another `reducedDim`. 

So overall, if we really want a separate slot (or store them in `int_colData`, see #43), they should behave identical to the rest: a `DFrame` and nothing else. 

Similarly, I think it is logical for `spatialCoords` to behave like a `reducedDim`, i.e. a matrix and nothing else. 

Finally, for visualization, it's worth keeping in mind that any `cbind(Dframe, matrix, data.frame)` will anyways coheres all to a `DFrame`, no matter what we return for `spatialData/Coords`. So one will always have to call `data.frame(colData(.), spatialData(.), t(assay(.)), ...)` for `ggplot2`; this shouldn't affect our design choice. 

What would make everything easier in my opinion would be to simply write everything spatial into `colData`, which are directly accessible for visualisation using e.g. `scater`, and have a designated `int_colData` slot named `spatialCoords` (which is exactly how `reducedDims` are stored btw...). This would make the overall structure more robust and fully consistent to a normal SCE.

**Comment by HelenaLC** [comment]
Current plan from meeting (related to #43):

- add `int_colData()` column `spatialCoords` (fixed to a numeric matrix)
- add `int_metadata()` slot `spatialDataNames` to track `colData` columns that store spatially-related data
- remove `@spatialData` slot and move these to `colData`
- `spatialData()` accessor should return a subset of `colData` according to `int_metadata()$spatialDataNames`
- `spatialCoords()/Names()` should return the content / names of `int_colData()$spatialCoords`
- (optional) `spatialData()` could support an argument `spatialCoords = TRUE/FALSE` specifying whether or not to include `spatialCoords` (default TRUE?) and `colData = TRUE/FALSE / character vector` specifying whether or not / which `colData` to include (default FALSE?)

**Comment by HelenaLC** [comment]
Resolved by PR #46 
- `spatialData` are now a subset of `colData` specified by `int_metadata` field `spatialDataNames`
- as a results, the `spatialData` accessor always returns a `DFrame`
- for additional flexibility, the accessor also allows inclusion of `spatialCoords` and `colData` (or a subset thereof)
