### ISSUE TITLE
colData show method with spatialData = FALSE and spatialCoords = FALSE arguments

### ISSUE THREAD

**Issue by lmweber** [drighelli/SpatialExperiment#69]
For discussion at our next meeting:

Should we add arguments to the `colData()` show method to include or exclude `spatialData` and `spatialCoords` columns?

So then we would have the following arguments and defaults in the show methods:
`colData(spe, spatialData = FALSE, spatialCoords = FALSE)`
`spatialData(spe, spatialCoords = FALSE)`
`spatialCoords(spe)`

I like this because it is "symmetrical" and hierarchical, i.e. each show method shows only the minimal columns by default, but the user can turn on additional columns by changing the arguments to TRUE.

I tried this in my previous attempt to solve #66 , but we didn't need it there due to the additional solution @drighelli found.

We could also remove the argument `spatialData(spe, colData = TRUE/FALSE)` in this case (users can just `cbind` instead), so that it is hierarchical, i.e. `colData > spatialData > spatialCoords`. I have been using `cbind` and pipes for plotting with `ggplot` for this, which seems to work well.

**Comment by drighelli** [comment]
I like the idea, but I tried to work on your implementation and there was always something that didn't work.

We'll discuss about it on our next meeting on Monday :)

**Comment by lmweber** [comment]
Just summarizing from our meeting today - I think this will only need to affect the getter method (not setter), which should make things a lot simpler.

**Comment by HelenaLC** [comment]
Okay, I spent ~2h on this and there're some deeper-rooted issues (I think) that aren't straightforward to resolve:
- I agree that, in principle, the hierarchy above makes a lot for sense. However,
- We currently don't store the `spatialData` in a separate slot or the `int_colData`, they are simply tracked via `spatialDataNames` in the `int_metadata`.
- So, if we overwrite the SE `colData` getter to not include them, they will be dropped, for example, when `cbind`ing two SPEs.
- As `spatialData` are currently part of the `colData`, one might argue they should be (by default) included. Or otherwise should be stored separately in the `int_colData`.
- I can get around all this for all methods except the `cbind`ing, which could probably be hacked easily. However, still doubtful because in summary:
- If we follow the above logic of a hierarchy, `spatialData` should go separate `int_colData`, which goes against previous discussions we had to make them part of the `colData` for direct accessibility. But, while I agree that having redundancy in the SPE `show` method is confusion, it's also weird to store them in the `colData` and then not return them (by default)... Thoughts?

**Comment by drighelli** [comment]
Thanks Helena, I got the same problems when trying to fix https://github.com/drighelli/SpatialExperiment/issues/66 , that's why in the end I came up with a different solution.

Generally speaking, if this becomes too much difficult, I'd drop the idea of adding these flags to the `colData` getter method.

Otherwise, we have to think the `colData`/`spatialData` structure in a different way, as you were suggesting...

**Comment by lmweber** [comment]
Ok, thanks for looking into it @HelenaLC and @drighelli .

Does it work if we add the arguments to the getters, but have default values of `TRUE` (instead of `FALSE`)? Then the default behavior could be the same as now, but we would still have the options for displaying with/without depending on user preference. Would this be useful in some of our vignette examples?

**Comment by drighelli** [comment]
I think we can give this idea a shot, but we have to heavily test all the methods with the flags equal to `FALSE`.
I guess we can face the same "loop-problem" in that case.

**Comment by drighelli** [comment]
We discussed this issue today and @HelenaLC proposed to leave the actual methods hierarchy with
`colData`, `spatialData` and `spatialCoords`, but moving the spatialData storage from the `colData` to the `int_colData`.

In this way it should be easier to implement the flags as suggested by @lmweber and for us to maintain the object.

If this sounds good for you, Lukas, Helena proposed to do the new implementation while I'll update the vignette with these updates.

I hope I'm not missing anything ^^'

**Comment by lmweber** [comment]
Ok, that sounds good, thanks! So from a user perspective this wouldn't change much, correct? But it would make ongoing maintenance simpler, and give us the ability to more easily do things like adding arguments to accessors.

**Comment by HelenaLC** [comment]
Almost, changes from a user-perspective would be, in my opinion, minor and defendable. Couple more or less obvious examples:
- `spe$in_tissue` -> `spatialData(spe)$in_tissue`... but this won't be needed for 90% of analysis I think.
- `colData(spe)` default won't include the spatial data -> `colData(spe, TRUE)` or `cbind(colData(spe), spatialData(spe))`
- we discussed sample IDs should remain in the `colData`, to be directly accessible (separate from the `spatialData`), agreed?
...can't think of more now. But def. the implementation will be much cleaner this way!

**Comment by lmweber** [comment]
Ah yes - yes, I think these changes are all okay, and we can make sure the vignette examples are all updated and consistent if they are affected.
