### ISSUE TITLE
Is R 4.0.0 required? 

### ISSUE THREAD

**Issue by zhiiiyang** [drighelli/SpatialExperiment#7]
Hello, thank you for making the great R S4 class. I noticed that you have required R version to be at least 4.0.0. May I ask whether it is absolutely necessary to upgrade my R version to be 4.0.0 in order to use this package? Mine is still 3.6.3. I was able to install this package by lowering the R version in the description file. But I am wondering whether it will be any potential pitfalls for not doing so? Thank you so much.

**Comment by drighelli** [comment]
Hi @zhiiiyang,

Thanks for your question, I do not recommend to lower the version into the DESCRIPTION file by yourself, please install it from Bioconductor devel.

Because the package is available on Bioconductor development version, the package itself has been developed using R 4.0.0.
Several things changed during this R upgrade that can affect the future development of this package and its actual and future dependencies.

If you want to use it in a lower version of R it's on your own "risk", but of course, bugs can raise...

Hope this helps! :)
Dario

**Comment by zhiiiyang** [comment]
@drighelli, thank you for clarifying this!
