### ISSUE TITLE
Backward compatibility in spatialData accessor

### ISSUE THREAD

**Issue by lmweber** [drighelli/SpatialExperiment#96]
I wonder if it is worth including some additional backward compatibility in the `spatialData()` accessor, as follows.

Current version of accessor:
```
setMethod("spatialData", 
    "SpatialExperiment",
    function(x) {
      colData(x)[spatialDataNames(x)]
    }
)
```

More backward compatibility:
```
setMethod("spatialData", 
    "SpatialExperiment",
    function(x) {
      spd <- colData(x)[spatialDataNames(x)]
      if (ncol(spd) == 0 & !is.null(int_colData(x)$spatialData) {
        spd <- int_colData(x)$spatialData
      }
      spd
    }
)
```

This would mean that objects previously created with SPE version < 1.5.2 with `spatialData` stored in `int_colData` can still be easily accessed.

What do you think? Useful or overcomplicating things?

**Comment by drighelli** [comment]
I think it could be useful to introduce this patch to the new version of the `spatialData` accessor.

It's not overcomplicating in my opinion, this improves the object robustness.

The only thing I'm worried about is how we manage the forward versions, do we want to remove the `spatialData` accessor in the future? If this is the case we have to print a warning about the version compatibility or we can automatically convert the object to the newer version (this last one is the `SingleCellExperiment` approach if I remember rightly).

**Comment by lmweber** [comment]
Thanks, yes we will need to think about how exactly to best get rid of `spatialData` completely at some point in the future. For now I have made the warning message a bit more descriptive/clear (also in the pull request above), so users will at least know about the issue.

**Comment by HelenaLC** [comment]
I think your thinking is really good @lmweber, but I'm personally not in favour of adding (what might look like) arbitrary code to check for things that might or might not exist in older versions. There will come a time when we'll again have other class-changes, and accounting for these through checks as the above will become more and more difficult. So, as @drighelli mentioned, I think we should at this point definitely start version-tracking objects as in the SCE; and, rather than adapting accessors, write conversion functions from old -> new such that all current functions work as they are supposed to at the moment (that is, the current version).

**Comment by lmweber** [comment]
Yeah that's fair, maybe it's overcomplicating things too much for too little benefit in the end.

I think there are arguments both ways here, so it's also fine for me if we skip this one and don't merge it.

Agree in the longer term versioning will be useful, especially if e.g. we have some bigger change for a new technological platform or similar.
